[
  {
    "script_path": "v2/tutorials/code_runner/agent.py",
    "status": "failed",
    "duration": 0.20473790168762207,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "",
    "stderr": "  \u00d7 No solution found when resolving script dependencies:\n  \u2570\u2500\u25b6 Because only flyte<=2.0.0b22 is available and you require flyte>=2.0.0b23, we can conclude that your requirements are unsatisfiable.\n"
  },
  {
    "script_path": "v2/tutorials/text_to_sql/create_qa_dataset.py",
    "status": "failed",
    "duration": 3.7714359760284424,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "15:41:14.213324 WARNING  remote_builder.py:89 -  Image text-to-sql:9c77072d37d5f0010dd8c9f7d8b4ac44 was not found or has expired.                               \nFiltered traceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/text_to_sql/create_qa_dataset.py\", line 279, in <module>\n    run = flyte.run(build_eval_dataset)\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_run.py\", line 635, in run\n    return await _Runner().run.aio(task, *args, **kwargs)  # type: ignore\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_run.py\", line 523, in run\n    return await self._run_remote(task, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_run.py\", line 165, in _run_remote\n    image_cache = await build_images.aio(cast(Environment, obj.parent_env()))\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_deploy.py\", line 285, in build_images\n    return await _build_images(deployment[0])\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_deploy.py\", line 160, in _build_images\n    final_images = await asyncio.gather(*images)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_deploy.py\", line 141, in _build_image_bg\n    return env_name, await build.aio(image)\n                     ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_build.py\", line 26, in build\n    return await ImageBuildEngine.build(image)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/async_lru/__init__.py\", line 221, in __call__\n    return await asyncio.shield(fut)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_internal/imagebuild/image_builder.py\", line 206, in build\n    image.validate()\n    ~~~~~~~~~~~~~~^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_image.py\", line 450, in validate\n    layer.validate()\n    ~~~~~~~~~~~~~~^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/create-qa-dataset-5a8a58594181f1b7/lib/python3.13/site-packages/flyte/_image.py\", line 300, in validate\n    raise ValueError(f\"Source folder {self.src.absolute()} does not exist\")\n\nValueError: Source folder /Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/text_to_sql/ground_truth.csv does not exist\n\n",
    "stderr": ""
  },
  {
    "script_path": "v2/tutorials/text_to_sql/text_to_sql.py",
    "status": "failed",
    "duration": 0.2415180206298828,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "Filtered traceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/text_to_sql/text_to_sql.py\", line 15, in <module>\n    from data_ingestion import TableInfo, data_ingestion\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/text_to_sql/data_ingestion.py\", line 8, in <module>\n    import pandas as pd\n\nModuleNotFoundError: No module named 'pandas'\n\n",
    "stderr": "Installed 86 packages in 102ms\n"
  },
  {
    "script_path": "v2/tutorials/text_to_sql/optimizer.py",
    "status": "failed",
    "duration": 14.015713930130005,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "15:41:28.441403 WARNING  remote_builder.py:89 -  Image text-to-sql:9c77072d37d5f0010dd8c9f7d8b4ac44 was not found or has expired.                               \nFiltered traceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/text_to_sql/optimizer.py\", line 649, in <module>\n    run = flyte.run(auto_prompt_engineering)\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_run.py\", line 635, in run\n    return await _Runner().run.aio(task, *args, **kwargs)  # type: ignore\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_run.py\", line 523, in run\n    return await self._run_remote(task, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_run.py\", line 165, in _run_remote\n    image_cache = await build_images.aio(cast(Environment, obj.parent_env()))\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_deploy.py\", line 285, in build_images\n    return await _build_images(deployment[0])\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_deploy.py\", line 160, in _build_images\n    final_images = await asyncio.gather(*images)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_deploy.py\", line 141, in _build_image_bg\n    return env_name, await build.aio(image)\n                     ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_build.py\", line 26, in build\n    return await ImageBuildEngine.build(image)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/async_lru/__init__.py\", line 221, in __call__\n    return await asyncio.shield(fut)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_internal/imagebuild/image_builder.py\", line 206, in build\n    image.validate()\n    ~~~~~~~~~~~~~~^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_image.py\", line 450, in validate\n    layer.validate()\n    ~~~~~~~~~~~~~~^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-ca356d8479a57e35/lib/python3.13/site-packages/flyte/_image.py\", line 300, in validate\n    raise ValueError(f\"Source folder {self.src.absolute()} does not exist\")\n\nValueError: Source folder /Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/text_to_sql/ground_truth.csv does not exist\n\n",
    "stderr": "Installed 91 packages in 135ms\n"
  },
  {
    "script_path": "v2/tutorials/ml/optimizer.py",
    "status": "failed",
    "duration": 26.284937858581543,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "15:41:32.589441 WARNING  remote_builder.py:89 -  Image optimizer:cf4ab60813e77374fc054cc080850f94 was not found or has expired.                                 \n15:41:33.712324 WARNING  remote_builder.py:112 -  \ud83d\udc33 Submitting a new build...                                                                                  \n15:41:34.098073 WARNING  remote_builder.py:119 -  \u23f3 Waiting for build to finish at:                                                                            \n                         https://playground.canary.unionai.cloud/v2/runs/project/system/domain/production/r75v24kzn4znhdzg8bt7                                  \n\nFiltered traceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/ml/optimizer.py\", line 202, in <module>\n    run = flyte.run(optimize, 100, 10)\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/flyte/_run.py\", line 635, in run\n    return await _Runner().run.aio(task, *args, **kwargs)  # type: ignore\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/flyte/_run.py\", line 523, in run\n    return await self._run_remote(task, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/flyte/_run.py\", line 165, in _run_remote\n    image_cache = await build_images.aio(cast(Environment, obj.parent_env()))\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/flyte/_deploy.py\", line 285, in build_images\n    return await _build_images(deployment[0])\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/flyte/_deploy.py\", line 160, in _build_images\n    final_images = await asyncio.gather(*images)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/flyte/_deploy.py\", line 141, in _build_image_bg\n    return env_name, await build.aio(image)\n                     ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/flyte/_build.py\", line 26, in build\n    return await ImageBuildEngine.build(image)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/async_lru/__init__.py\", line 221, in __call__\n    return await asyncio.shield(fut)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/flyte/_internal/imagebuild/image_builder.py\", line 215, in build\n    result = await img_builder.build_image(image, dry_run=dry_run)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/optimizer-787050d44867b16b/lib/python3.13/site-packages/flyte/_internal/imagebuild/remote_builder.py\", line 129, in build_image\n    raise flyte.errors.ImageBuildError(f\"\u274c Build failed in {elapsed} at [cyan]{run.url}[/cyan]\")\n\nImageBuildError: \u274c Build failed in 0:00:21 at [cyan]https://playground.canary.unionai.cloud/v2/runs/project/system/domain/production/r75v24kzn4znhdzg8bt7[/cyan]\n\n",
    "stderr": ""
  },
  {
    "script_path": "v2/tutorials/trading_agents/main.py",
    "status": "failed",
    "duration": 62.88228917121887,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "15:42:19.097970 WARNING  remote_builder.py:89 -  Image trading-agents:2dd8d7474d05701e3a266678ed4cfadb was not found or has expired.                            \n15:42:20.097583 WARNING  remote_builder.py:112 -  \ud83d\udc33 Submitting a new build...                                                                                  \n15:42:20.540774 WARNING  remote_builder.py:119 -  \u23f3 Waiting for build to finish at:                                                                            \n                         https://playground.canary.unionai.cloud/v2/runs/project/system/domain/production/rkl2f6cqscggfd7tcw7f                                  \n\n15:42:54.945015 WARNING  remote_builder.py:127 -  \u2705 Build completed in 0:00:35!                                                                                \n15:42:55.755981 WARNING  _deploy.py:163 -  Built Image for environment trading-agents, image:                                                                   \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:trading-agents-2dd8d7474d05701e3a266678ed4cfadb                          \nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/rkbggpvd5ccm925nbghc\nRun 'rkbggpvd5ccm925nbghc' exited unsuccessfully in state PHASE_FAILED with error: admission webhook \"flyte-pod-webhook.flyte.org\" denied the request: none of the secret managers injected secret : failed to inject secret  using any of the enabled secret managers: [Global AWS Embedded]. \nPossible reasons: the secret cannot be found or an internal error occurred\n\n",
    "stderr": "Downloading matplotlib (7.8MiB)\nDownloading tokenizers (2.8MiB)\nDownloading fonttools (2.7MiB)\nDownloading hf-xet (2.5MiB)\nDownloading curl-cffi (2.9MiB)\nDownloading chainlit (9.2MiB)\nDownloading lxml (8.2MiB)\nDownloading botocore (13.3MiB)\nDownloading langchain-community (2.4MiB)\nDownloading mini-racer (13.9MiB)\nDownloading akshare (1.0MiB)\nDownloading pandas (10.2MiB)\n   Building peewee==3.18.2\n   Building literalai==0.1.201\n   Building multitasking==0.0.12\n   Building jsonpath==0.82.2\n   Building syncer==2.0.3\n   Building sgmllib3k==1.0.0\n      Built syncer==2.0.3\n      Built sgmllib3k==1.0.0\n      Built jsonpath==0.82.2\n Downloading akshare\n      Built literalai==0.1.201\n Downloading hf-xet\n Downloading tokenizers\n Downloading curl-cffi\n Downloading fonttools\n Downloading langchain-community\n      Built multitasking==0.0.12\n Downloading matplotlib\n Downloading chainlit\n Downloading lxml\n Downloading botocore\n Downloading pandas\n Downloading mini-racer\n      Built peewee==3.18.2\nInstalled 226 packages in 350ms\n"
  },
  {
    "script_path": "v2/tutorials/deep_research_agent/agent.py",
    "status": "failed",
    "duration": 91.75756025314331,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "15:43:05.491930 WARNING  remote_builder.py:89 -  Image deep-research-agent:2557e59ffa58efe58aaa83b3f4bea340 was not found or has expired.                       \n15:43:07.048885 WARNING  remote_builder.py:112 -  \ud83d\udc33 Submitting a new build...                                                                                  \n15:43:07.459307 WARNING  remote_builder.py:119 -  \u23f3 Waiting for build to finish at:                                                                            \n                         https://playground.canary.unionai.cloud/v2/runs/project/system/domain/production/rxslcx8jt6tjnggmdjvc                                  \n\n15:44:27.652444 WARNING  remote_builder.py:127 -  \u2705 Build completed in 0:01:20!                                                                                \n15:44:27.951049 WARNING  _deploy.py:163 -  Built Image for environment deep-researcher, image:                                                                  \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:deep-research-agent-2557e59ffa58efe58aaa83b3f4bea340                     \nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/rhmrcjngvwjgzws9pjg4\nRun 'rhmrcjngvwjgzws9pjg4' exited unsuccessfully in state PHASE_FAILED with error: admission webhook \"flyte-pod-webhook.flyte.org\" denied the request: none of the secret managers injected secret : failed to inject secret  using any of the enabled secret managers: [Global AWS Embedded]. \nPossible reasons: the secret cannot be found or an internal error occurred\n\n",
    "stderr": "Downloading litellm (7.6MiB)\n Downloading litellm\nInstalled 85 packages in 125ms\n"
  },
  {
    "script_path": "v2/tutorials/deep_research_agent/weave_evals.py",
    "status": "failed",
    "duration": 16.08062720298767,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "2025-09-26 15:44:47 - weave.trace.weave_init - INFO - Please login to Weights & Biases (https://wandb.ai/) to continue...\nFiltered traceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/deep_research_agent/weave_evals.py\", line 27, in <module>\n    weave.init(project_name=\"deep-researcher\")\n    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/weave-evals-fb92d39e514772bc/lib/python3.13/site-packages/weave/trace/api.py\", line 85, in init\n    initialized_client = weave_init.init_weave(\n        project_name,\n        autopatch_settings=autopatch_settings,\n    )\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/weave-evals-fb92d39e514772bc/lib/python3.13/site-packages/weave/trace/weave_init.py\", line 112, in init_weave\n    wandb.login(anonymous=\"never\", force=True)  # type: ignore\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/weave-evals-fb92d39e514772bc/lib/python3.13/site-packages/wandb/sdk/wandb_login.py\", line 80, in login\n    return _login(\n        anonymous=anonymous,\n    ...<6 lines>...\n        referrer=referrer,\n    )\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/weave-evals-fb92d39e514772bc/lib/python3.13/site-packages/wandb/sdk/wandb_login.py\", line 318, in _login\n    key, key_status = wlogin.prompt_api_key(referrer=referrer)\n                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/weave-evals-fb92d39e514772bc/lib/python3.13/site-packages/wandb/sdk/wandb_login.py\", line 244, in prompt_api_key\n    raise UsageError(\"api_key not configured (no-tty). call \" + directive)\n\nUsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])\n\n",
    "stderr": "Downloading wandb (17.5MiB)\n Downloading wandb\nInstalled 103 packages in 183ms\n\u001b[36m\u001b[1mweave\u001b[0m: Please login to Weights & Biases (https://wandb.ai/) to continue...\n"
  },
  {
    "script_path": "v2/tutorials/auto_prompt_engineering/optimizer.py",
    "status": "failed",
    "duration": 36.88695311546326,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "15:44:57.833637 WARNING  remote_builder.py:89 -  Image auto-prompt-engineering:5e53ce9ee9188ffece6dbc558a5a4653 was not found or has expired.                   \n15:44:58.863993 WARNING  remote_builder.py:112 -  \ud83d\udc33 Submitting a new build...                                                                                  \n15:44:59.266250 WARNING  remote_builder.py:119 -  \u23f3 Waiting for build to finish at:                                                                            \n                         https://playground.canary.unionai.cloud/v2/runs/project/system/domain/production/r4vjtnkmdzlwj8ksf4w8                                  \n\n15:45:20.706624 WARNING  remote_builder.py:127 -  \u2705 Build completed in 0:00:22!                                                                                \n15:45:21.040705 WARNING  _deploy.py:163 -  Built Image for environment auto-prompt-engineering, image:                                                          \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:auto-prompt-engineering-5e53ce9ee9188ffece6dbc558a5a4653                 \nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/rp5tqpw5hf7hzhw9vzl8\nRun 'rp5tqpw5hf7hzhw9vzl8' exited unsuccessfully in state PHASE_FAILED with error: admission webhook \"flyte-pod-webhook.flyte.org\" denied the request: none of the secret managers injected secret : failed to inject secret  using any of the enabled secret managers: [Global AWS Embedded]. \nPossible reasons: the secret cannot be found or an internal error occurred\n\n",
    "stderr": "Downloading litellm (8.4MiB)\n Downloading litellm\nInstalled 82 packages in 172ms\n"
  },
  {
    "script_path": "v2/tutorials/deep_research_agent/libs/utils/tavily_search.py",
    "status": "failed",
    "duration": 0.9568169116973877,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "Filtered traceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/deep_research_agent/libs/utils/tavily_search.py\", line 127, in <module>\n    print(asyncio.run(atavily_search_results(\"What is the capital of France?\")))\n          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.local/share/uv/python/cpython-3.13.5-macos-aarch64-none/lib/python3.13/asyncio/runners.py\", line 195, in run\n    return runner.run(main)\n           ~~~~~~~~~~^^^^^^\n  File \"/Users/ppiegaze/.local/share/uv/python/cpython-3.13.5-macos-aarch64-none/lib/python3.13/asyncio/runners.py\", line 118, in run\n    return self._loop.run_until_complete(task)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/Users/ppiegaze/.local/share/uv/python/cpython-3.13.5-macos-aarch64-none/lib/python3.13/asyncio/base_events.py\", line 725, in run_until_complete\n    return future.result()\n           ~~~~~~~~~~~~~^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/tavily-search-7c82fb0c1917def3/lib/python3.13/site-packages/flyte/_trace.py\", line 62, in wrapper_async\n    return await coroutine_result\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/deep_research_agent/libs/utils/tavily_search.py\", line 112, in atavily_search_results\n    raise ValueError(\"TAVILY_API_KEY environment variable is not set\")\n\nValueError: TAVILY_API_KEY environment variable is not set\n\n",
    "stderr": "Installed 50 packages in 35ms\n"
  },
  {
    "script_path": "v2/tutorials/trading_agents/agents/utils/memory.py",
    "status": "failed",
    "duration": 1.261080265045166,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "",
    "stderr": "Downloading botocore (13.4MiB)\n Downloading botocore\nInstalled 23 packages in 45ms\nTraceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/trading_agents/agents/utils/memory.py\", line 116, in <module>\n    matcher = FinancialSituationMemory(\n        name=\"trader\",\n    ...<3 lines>...\n        bucket_name=\"text-embeddings\",\n    )\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/tutorials/trading_agents/agents/utils/memory.py\", line 30, in __init__\n    self.openai_client = OpenAI()\n                         ~~~~~~^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/memory-7dac06b57c5982dc/lib/python3.13/site-packages/openai/_client.py\", line 135, in __init__\n    raise OpenAIError(\n        \"The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable\"\n    )\nopenai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable\n"
  },
  {
    "script_path": "v2/integrations/flyte-plugins/openai/openai/agents_tools.py",
    "status": "passed",
    "duration": 42.15307688713074,
    "exit_code": 0,
    "error_message": null,
    "stdout": "15:45:30.506492 WARNING  remote_builder.py:89 -  Image openai_agents_image:0732952df1c5a128525bbfab44b1caa9 was not found or has expired.                       \n15:45:31.487286 WARNING  remote_builder.py:112 -  \ud83d\udc33 Submitting a new build...                                                                                  \n15:45:31.848476 WARNING  remote_builder.py:119 -  \u23f3 Waiting for build to finish at:                                                                            \n                         https://playground.canary.unionai.cloud/v2/runs/project/system/domain/production/rmqn5ndv2nq7h2lgps86                                  \n\n15:45:38.152574 WARNING  remote_builder.py:127 -  \u2705 Build completed in 0:00:06!                                                                                \n15:45:38.434480 WARNING  _deploy.py:163 -  Built Image for environment openai_agents_tools, image:                                                              \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:openai_agents_image-0732952df1c5a128525bbfab44b1caa9                     \nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/rhvfz4xgfft9qjb49sx9\nRun 'rhvfz4xgfft9qjb49sx9' completed successfully.\n\n",
    "stderr": "Installed 69 packages in 62ms\n"
  },
  {
    "script_path": "v2/user-guide/getting-started/hello.py",
    "status": "passed",
    "duration": 19.675321102142334,
    "exit_code": 0,
    "error_message": null,
    "stdout": "15:46:10.076878 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22 found. Skip         \n                         building.                                                                                                                              \n15:46:10.077828 WARNING  _deploy.py:163 -  Built Image for environment hello_world, image:                                                                      \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22                                                   \nr7d7vqp4dvdxj98ktcjw\nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/r7d7vqp4dvdxj98ktcjw\nRun 'r7d7vqp4dvdxj98ktcjw' completed successfully.\n\n",
    "stderr": ""
  },
  {
    "script_path": "v2/user-guide/task-programming/error-handling/error_handling.py",
    "status": "failed",
    "duration": 0.35295891761779785,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "Filtered traceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/user-guide/task-programming/error-handling/error_handling.py\", line 46, in <module>\n    flyte.init_from_config(\"config.yaml\")\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/error-handling-eea3a08d4ae14182/lib/python3.13/site-packages/flyte/_initialize.py\", line 269, in init_from_config\n    raise InitializationError(\n    ...<3 lines>...\n    )\n\nInitializationError: Configuration file 'config.yaml' does not exist., current working directory is /Users/ppiegaze/repos/unionai/unionai-examples/v2/user-guide/task-programming/error-handling\n\n",
    "stderr": "Installed 44 packages in 35ms\n"
  },
  {
    "script_path": "v2/user-guide/task-programming/reports/streaming_reports.py",
    "status": "passed",
    "duration": 77.57237792015076,
    "exit_code": 0,
    "error_message": null,
    "stdout": "15:46:31.418423 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22 found. Skip         \n                         building.                                                                                                                              \n15:46:31.422298 WARNING  _deploy.py:163 -  Built Image for environment streaming_reports, image:                                                                \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22                                                   \nRun Name: rlrbtj5r27jjk8d55pjq\nRun URL: https://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/rlrbtj5r27jjk8d55pjq\nRun 'rlrbtj5r27jjk8d55pjq' completed successfully.\n\n",
    "stderr": "Installed 44 packages in 28ms\n"
  },
  {
    "script_path": "v2/user-guide/task-programming/reports/globe_visualization.py",
    "status": "passed",
    "duration": 11.900277853012085,
    "exit_code": 0,
    "error_message": null,
    "stdout": "15:47:49.034849 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22 found. Skip         \n                         building.                                                                                                                              \n15:47:49.037578 WARNING  _deploy.py:163 -  Built Image for environment globe_visualization, image:                                                              \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22                                                   \nr428zncpnl2nkd9mw9jf\nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/r428zncpnl2nkd9mw9jf\nRun 'r428zncpnl2nkd9mw9jf' completed successfully.\n\n",
    "stderr": "Installed 44 packages in 33ms\n"
  },
  {
    "script_path": "v2/user-guide/task-configuration/retries-and-timeouts/retries.py",
    "status": "passed",
    "duration": 43.93834400177002,
    "exit_code": 0,
    "error_message": null,
    "stdout": "15:48:00.943842 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22 found. Skip         \n                         building.                                                                                                                              \n15:48:00.948596 WARNING  _deploy.py:163 -  Built Image for environment my-env, image:                                                                           \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22                                                   \nrqjhvx9s8gmjf2p7zvqt\nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/rqjhvx9s8gmjf2p7zvqt\nRun 'rqjhvx9s8gmjf2p7zvqt' completed successfully.\n\n",
    "stderr": "Installed 44 packages in 31ms\n"
  },
  {
    "script_path": "v2/user-guide/task-configuration/retries-and-timeouts/timeouts.py",
    "status": "passed",
    "duration": 75.15554594993591,
    "exit_code": 0,
    "error_message": null,
    "stdout": "15:48:44.924213 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22 found. Skip         \n                         building.                                                                                                                              \n15:48:44.929313 WARNING  _deploy.py:163 -  Built Image for environment my-env, image:                                                                           \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-py3.13-v2.0.0b22                                                   \nrcmqrhllm4rg454fqlfz\nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/rcmqrhllm4rg454fqlfz\nRun 'rcmqrhllm4rg454fqlfz' completed successfully.\n\n",
    "stderr": "Installed 44 packages in 31ms\n"
  },
  {
    "script_path": "v2/user-guide/task-configuration/container-images/debian-image-example.py",
    "status": "failed",
    "duration": 2.784381151199341,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "Filtered traceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/user-guide/task-configuration/container-images/debian-image-example.py\", line 46, in <module>\n    flyte.init_from_config(\"config.yaml\")\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/debian-image-example-477b3f6ce28e1df5/lib/python3.13/site-packages/flyte/_initialize.py\", line 269, in init_from_config\n    raise InitializationError(\n    ...<3 lines>...\n    )\n\nInitializationError: Configuration file 'config.yaml' does not exist., current working directory is /Users/ppiegaze/repos/unionai/unionai-examples/v2/user-guide/task-configuration/container-images\n\n",
    "stderr": "Downloading polars (34.0MiB)\n Downloading polars\nInstalled 45 packages in 30ms\n"
  },
  {
    "script_path": "v2/user-guide/task-configuration/container-images/uv-image-example.py",
    "status": "failed",
    "duration": 1.4545869827270508,
    "exit_code": 1,
    "error_message": "Exit code 1",
    "stdout": "Filtered traceback (most recent call last):\n  File \"/Users/ppiegaze/repos/unionai/unionai-examples/v2/user-guide/task-configuration/container-images/uv-image-example.py\", line 46, in <module>\n    flyte.init_from_config(\"config.yaml\")\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Users/ppiegaze/.cache/uv/environments-v2/uv-image-example-46226f4fb3c0baf1/lib/python3.13/site-packages/flyte/_initialize.py\", line 269, in init_from_config\n    raise InitializationError(\n    ...<3 lines>...\n    )\n\nInitializationError: Configuration file 'config.yaml' does not exist., current working directory is /Users/ppiegaze/repos/unionai/unionai-examples/v2/user-guide/task-configuration/container-images\n\n",
    "stderr": "Installed 45 packages in 30ms\n"
  },
  {
    "script_path": "v2/user-guide/task-configuration/reusable-containers/reuse-concurrency.py",
    "status": "passed",
    "duration": 24.38030695915222,
    "exit_code": 0,
    "error_message": null,
    "stdout": "15:50:04.462617 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-5f14c17bd47ec79fe2306dae4d0ba7ce     \n                         found. Skip building.                                                                                                                  \n15:50:04.466101 WARNING  _deploy.py:163 -  Built Image for environment reuse_concurrency, image:                                                                \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-5f14c17bd47ec79fe2306dae4d0ba7ce                                   \nr4mh84phr4mrgbqjl9qs\nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/r4mh84phr4mrgbqjl9qs\nRun 'r4mh84phr4mrgbqjl9qs' completed successfully.\n\n",
    "stderr": "Installed 44 packages in 27ms\n"
  },
  {
    "script_path": "v2/user-guide/task-configuration/reusable-containers/reuse-ml.py",
    "status": "passed",
    "duration": 22.592579126358032,
    "exit_code": 0,
    "error_message": null,
    "stdout": "15:50:28.618974 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-a793e417a84226c1dd726eab07c3dcdd     \n                         found. Skip building.                                                                                                                  \n15:50:28.624218 WARNING  _deploy.py:163 -  Built Image for environment ml_env, image:                                                                           \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-a793e417a84226c1dd726eab07c3dcdd                                   \nr4gx8c7kq9px5lhr2jqp\nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/r4gx8c7kq9px5lhr2jqp\nRun 'r4gx8c7kq9px5lhr2jqp' completed successfully.\n\n",
    "stderr": "Installed 44 packages in 31ms\n"
  },
  {
    "script_path": "v2/user-guide/task-configuration/multiple-environments/af2/main.py",
    "status": "passed",
    "duration": 24.855119943618774,
    "exit_code": 0,
    "error_message": null,
    "stdout": "15:50:49.999966 INFO     _initialize.py:280 -  Flyte config initialized as Config(platform=PlatformConfig(endpoint='dns:///playground.canary.unionai.cloud',    \n                         client_id='union-docs', client_credentials_secret='xJkNiskn4ka2TlnPtAQPKhwIrpoklIvS3IcjD563tSgAhMT-3GY5jFUIFAoCdcor', scopes=[],       \n                         auth_mode='ClientSecret'), task=TaskConfig(org='playground', project='docs-examples', domain='development'),                           \n                         image=ImageConfig(builder='remote'), source=PosixPath('/Users/ppiegaze/repos/unionai/unionai-examples/tests/.flyte/config.yaml'))      \n15:50:50.535924 INFO     _deploy.py:140 -  Building image flyte for environment fold_env                                                                        \n15:50:50.536351 INFO     _deploy.py:140 -  Building image flyte for environment msa_env                                                                         \n15:50:50.536577 INFO     _deploy.py:140 -  Building image flyte for environment multi_env                                                                       \n15:50:51.245218 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-fbd40feef4ef78d53b991b5a1c800cf6     \n                         found. Skip building.                                                                                                                  \n15:50:51.248221 INFO     image_builder.py:218 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-fbd40feef4ef78d53b991b5a1c800cf6     \n                         already exists in registry. Skipping build.                                                                                            \n15:50:51.314139 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-fab60fde485044a8fc6a14889b48ab99     \n                         found. Skip building.                                                                                                                  \n15:50:51.317245 INFO     image_builder.py:218 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-fab60fde485044a8fc6a14889b48ab99     \n                         already exists in registry. Skipping build.                                                                                            \n15:50:51.412068 WARNING  remote_builder.py:86 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-453650bb1300708b10c550c93e743260     \n                         found. Skip building.                                                                                                                  \n15:50:51.414007 INFO     image_builder.py:218 -  Image 356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-453650bb1300708b10c550c93e743260     \n                         already exists in registry. Skipping build.                                                                                            \n15:50:51.415671 WARNING  _deploy.py:163 -  Built Image for environment fold_env, image:                                                                         \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-fab60fde485044a8fc6a14889b48ab99                                   \n15:50:51.416825 WARNING  _deploy.py:163 -  Built Image for environment msa_env, image:                                                                          \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-fbd40feef4ef78d53b991b5a1c800cf6                                   \n15:50:51.417644 WARNING  _deploy.py:163 -  Built Image for environment multi_env, image:                                                                        \n                         356633062068.dkr.ecr.us-east-2.amazonaws.com/union/playground:flyte-453650bb1300708b10c550c93e743260                                   \n15:50:51.452817 INFO     _packaging.py:29 -  Files to be copied for fast registration...                                                                        \n15:50:51.454131 INFO     _packaging.py:55 -  Root directory:                                                                                                    \n                         /Users/ppiegaze/repos/unionai/unionai-examples/v2/user-guide/task-configuration/multiple-environments/af2                              \n15:50:51.454506 INFO     _packaging.py:56 -  File structure:                                                                                                    \n                         \ud83d\udcc2 /Users/ppiegaze/repos/unionai/unionai-examples/v2/user-guide/task-configuration/multiple-environments/af2                           \n                         \u2523\u2501\u2501 fold                                                                                                                               \n                         \u2503   \u2523\u2501\u2501 __init__.py                                                                                                                    \n                         \u2503   \u2517\u2501\u2501 run.py                                                                                                                         \n                         \u2523\u2501\u2501 main.py                                                                                                                            \n                         \u2517\u2501\u2501 msa                                                                                                                                \n                             \u2523\u2501\u2501 __init__.py                                                                                                                    \n                             \u2517\u2501\u2501 run.py                                                                                                                         \n                                                                                                                                                                \n15:50:51.456928 INFO     bundle.py:148 -  Code bundle created at                                                                                                \n                         /var/folders/vn/72xlcb5d5jbbb3kk_q71sqww0000gn/T/tmpq1v4jn9d/fast2d2165670c3c8788d7467ef454a8dcd2.tar.gz, size: 0.01953125 MB, archive \n                         size: 0.0011577606201171875 MB                                                                                                         \nhttps://playground.canary.unionai.cloud/v2/runs/project/docs-examples/domain/development/rqvmgzmk8vtcmchr5zzs\nRun 'rqvmgzmk8vtcmchr5zzs' completed successfully.\n\n",
    "stderr": "Installed 44 packages in 28ms\n"
  }
]